# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

#app.jwt_auth:
#        class: AppBundle\Service\JwtAuth
#        arguments: ["@doctrine.orm.entity_manager"]
        
#app.helpers:
#        class: AppBundle\Service\Helpers
#        arguments: ["@app.jwt_auth"]